global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "cathedral_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'cathedral'
    static_configs:
      - targets: ['cathedral-app:3000']
    scrape_interval: 5s
    metrics_path: /metrics
    
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
      
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
