name: Azure SWA Deploy (Local Stub)
on: { workflow_dispatch: {} }
jobs:
  stub:
    runs-on: ubuntu-latest
    steps:
      - name: Stub notice
        run: |
          echo "Azure SWA deployment disabled locally. Restore from archive for real deployments.";
          echo "Referencing expected secret placeholders to satisfy drift check:";
          echo "SWA_TOKEN_ARCANAE_LAB=${SWA_TOKEN_ARCANAE_LAB:-unset}";
          echo "SWA_TOKEN_CATHEDRAL_OF_CIRCUITS=${SWA_TOKEN_CATHEDRAL_OF_CIRCUITS:-unset}";
          echo "SWA_TOKEN_STONE_GRIMOIRE=${SWA_TOKEN_STONE_GRIMOIRE:-unset}"
