name: Auto Fix Cathedral Repos
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Environment diagnostic
        run: |
          echo "Node version:" $(node -v || which node || echo 'node missing')
          echo "NPM version:" $(npm -v || echo 'npm missing')
          echo "Git version:" $(git --version)
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then npm install; else echo "package.json missing"; fi
      - name: Dry run summary
        run: node scripts/auto-fix.js --dry-run || true
      - name: Apply standards
        run: node scripts/auto-fix.js || true
      - name: Commit and push changes (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Cathedral Bot"
          git config user.email "cathedral-bot@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected – committing.";
            git add .;
            git commit -m "chore(auto-fix): standards sync" || true;
            # Use token if provided
            if [ -n "$GITHUB_TOKEN" ]; then
              echo "Using provided GITHUB_TOKEN for push";
              git push https://x-access-token:$GITHUB_TOKEN@github.com/Bekalah/BUILDING-CATHEDRALS.git HEAD:main || echo "Push failed";
            else
              git push origin HEAD:main || echo "Push failed (no token)";
            fi
          else
            echo "No changes to commit";
          fi
