version: '3.8'

services:
  cathedral-app:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.cathedral
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CATHEDRAL_ENV=development
    volumes:
      - ../../:/app
      - /app/node_modules
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=cathedral
      - POSTGRES_USER=cathedral
      - POSTGRES_PASSWORD=sacred_geometry_144
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  monitoring:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
