name: Auto Fix Cathedral Repos
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run autofix script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/auto-fix.js
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Cathedral Bot"
          git config user.email "cathedral-bot@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore(auto-fix): modularization + standards sync"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
