{
  "name": "cathedral-edge-router",
  "main": "cathedral-edge-router.js",
  "compatibility_date": "2024-10-01",
  "compatibility_flags": ["nodejs_compat"],
  "env": {
    "production": {
      "vars": {
        "ENVIRONMENT": "production"
      },
      "secrets": [
        "AZURE_FUNCTION_URL",
        "AZURE_FUNCTION_KEY"
      ]
    },
    "staging": {
      "vars": {
        "ENVIRONMENT": "staging"
      },
      "secrets": [
        "AZURE_FUNCTION_URL",
        "AZURE_FUNCTION_KEY"
      ]
    }
  },
  "routes": [
    "cathedral.your-domain.com/*",
    "*.cathedral.your-domain.com/*"
  ],
  "triggers": {
    "crons": []
  },
  "usage_model": "bundled"
}